# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 17 Apr 2022 13:06:49 +0000
*	@ALL	1
*	@user	1
aitohaltiat	@ALL	0
anrok_khex	@ALL	0
dyleskar	@ALL	0
dymayrrynth	@ALL	0
gurn_valittu	@ALL	0
iliss	@ALL	0
kampanja:*	@ALL	0
kuningas_iotr	@ALL	0
maroxxothin	@ALL	0
oktarin_laakson_aikajana	@ALL	0
pronssileikkuri	@ALL	0
pronssivaltakunta	@ALL	0
razomin_imperiumi	@ALL	0
rotujen_historia	@ALL	0
sammakonlallo	@ALL	0
sieluoppaat	@ALL	0
urthuxemur	@ALL	0
wraxiris_tulenluoma	@ALL	0
remia	@ALL	0
ocir_zammith_dm	@ALL	0
kaikkeusavain	@ALL	0
maailman_synty	@ALL	0
reku_huuhkahiippa	@ALL	0
