<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 05 Feb 2022 08:40:17 +0000
 */
$conf['title'] = 'Onigma';
$conf['tagline'] = 'Opas kaoottiseen maailmaan'
$conf['lang'] = 'fi';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['template'] = 'writr';
$conf['sidebar'] = 'sidebar';
$conf['maxseclevel'] = 0;