<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: zerahar
 * Date: Fri, 22 Apr 2022 06:26:49 +0000
 */

$conf['title'] = 'Onigma';
$conf['lang'] = 'fi';
$conf['template'] = 'onigmaDark';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['usewordblock'] = 0;
$conf['htmlok'] = 1;
$conf['locktime'] = 0;
$conf['cachetime'] = 0;
$conf['mediarevisions'] = 0;
$conf['plugin']['gallery']['options'] = 'lightbox';
$conf['plugin']['pagelist']['style'] = 'simplelist';
$conf['plugin']['pagelist']['showdate'] = '0';
$conf['plugin']['pagelist']['showuser'] = '0';
$conf['plugin']['pagelist']['showfirsthl'] = 0;
$conf['tpl']['onigma']['hideTools'] = 1;
