<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Sat, 05 Feb 2022 08:40:17 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
