# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sun, 17 Apr 2022 13:06:49 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

zerahar:$2y$10$R2QqTWog7gOwKNbOxgJsbumDYXjnvFaNO.ow.mvwU9HSO7x4DabNC:Heini Saastamoinen:heinisaastamoinen@gmail.com:admin,user
