# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 05 Feb 2022 08:40:17 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

zerahar:$2y$10$Wz9pbuNXnJUacQWqkr77feAmGKCzZ44F0Y4GChCslxXksbLwZp41i:Heini Saastamoinen:heinisaastamoinen@gmail.com:admin,user
